apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart
        image: mangesh22898/cart-service:latest
        ports:
        - containerPort: 7070
        env:
        - name: VALKEY_ADDR
          value: valkey-cart:6379
